### ISSUE TITLE
Where I can find contribution gide?

### ISSUE THREAD

**Issue by tomfun** [sigrlami/api-monobank#1]

**Comment by sigrlami** [comment]
Just started 3 hours ago. Later today, I'll push updated version and will be able to accept contributions.

**Comment by sigrlami** [comment]
@tomfun package operational with `servant-client`. There are small work with error required and updating example app. You can easily load in REPL with `stack repl` and use it interactively. For example, loading personal information:

```
repl> :load src/Monobank/Api.hs
repl> :set -XOverloadedStrings
repl> getPersonalInfo' (Just "bm90IHNvIGZhc3QgSm9obm55")
```

**Comment by sigrlami** [comment]
This commit adds afb50e397f9b39af74d2a9562adf8b204a86f45f `Contribution guide` through simple PR-based approach. Just fork repo add your corrections and submit for review.
